### ISSUE TITLE
CA certificate

### ISSUE THREAD

**Issue by igkhv** [kittoku/Open-SSTP-Client#10]
Please add a function to ignore the CA certificate

**Comment by kittoku** [comment]
I considered the option before, but I decided not to accept it. It is very risky even though this app is licensed under MIT. Non-experts might  accidentally enable the option without understanding what it means. Also, Google explicitly discourages the option.

If you really need to ignore certificates, you should modify the source code and build this app by yourself.

**Comment by pkasperskyi** [comment]
Is it about allowing self signed certificate / with CA set to TRUE? It's a common practice to use'm during test setup to prove the solution.. double warning with clear text + hiding under "advanced" option would be safe enough. In Windows you can just import the certificate & trust it - shouldn't the same pattern to be possible on Android?
