### ISSUE TITLE
Connesttion could not be estabilished

### ISSUE THREAD

**Issue by lordrak007** [kittoku/Open-SSTP-Client#108]
[2022-12-04 10:16:40.576] Establish VPN connection
[2022-12-04 10:16:40.975] OSC: ERR_UNEXPECTED
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I install private CA but it can be installed only to private user store. New androids (from 10) does not allow import to system store.
Could you add option to skip certificate verification or option to specify CA certificate folder?
Thank you

**Comment by kittoku** [comment]
Please use `Add Trusted Certificates` option. BTW, this client also uses user store. So there would be another problem in your certificate.

**Comment by lordrak007** [comment]
I added CA to user store and it did not help. I used Add Trusted Certificates option also with CA certificate and it did not work. When i put certificate itself to truted folder, then it start working.
