### ISSUE TITLE
Allowing the system services to access when enable app based rule

### ISSUE THREAD

**Issue by EvanCui** [kittoku/Open-SSTP-Client#121]
When "Enable App-Based Rule" is turned on, the client only allows the specified app to route through the connection, but some software relies on a specific system service to work, such as google play framework. In the app list, there is no google play framework listed, which results in the situation that, only the selected apps are routed through the connection, but not the dependent services.

Suggested change:
If the app based routing is based the process ids, it's better list all processes including the system services, so that I can select the corresponding services.
Or, if it's hard to list them all, add a new option to allow all system services to route through the connection, which seems to be a larger granular but unblocks some scenarios.

**Comment by kittoku** [comment]
Sorry, but handling services looks too complidated for this app's policy to implement.
