### ISSUE TITLE
CHAP error in android app open.sstp.client v1.6.5.1

### ISSUE THREAD

**Issue by MrFarazSubhani** [kittoku/Open-SSTP-Client#123]
Android App : open-sstp-client v1.6.5.1
establishing connection to sstp server in windows it works fine doesn't requires any certificates just put ( server address , name , pass ) and it connects but here in this app it throws this error i didn't know how to deal with please help me with this problem.

errors captured in logs : 
 CHAP: ERR_AUTHENTICATION_FAILED

**Comment by Azuriye** [comment]
Hello did you resolve this issue?

**Comment by MrFarazSubhani** [comment]
> Hello did you resolve this issue?

Not yet i searched over net but didn't got the solution may be i can't integrate with lack of coding knowledge

**Comment by Azuriye** [comment]
> Not yet i searched over net but didn't got the solution may be i can't integrate with lack of coding knowledge

I seem to get this issue after placing my files in /system/etc/security/cacerts

**Comment by MrFarazSubhani** [comment]
> > Not yet i searched over net but didn't got the solution may be i can't integrate with lack of coding knowledge
> 
> I seem to get this issue after placing my .cer files in /system/etc/security/cacerts

i think its about windows or linux ?
my question is related android app..
and i didn't have certificate
