### ISSUE TITLE
Launch activity on tile long press

### ISSUE THREAD

**Issue by bildin** [kittoku/Open-SSTP-Client#126]
Please add 
`<action android:name="android.service.quicksettings.action.QS_TILE_PREFERENCES"/>`
to MainActivity intent-filter.
This little change will increase usability for quick access to profile configuration.

**Comment by bildin** [comment]
Yes. Thanks!

сб, 17 февр. 2024 г., 19:38 KOBAYASHI Ittoku ***@***.***>:

**Comment by kittoku** [comment]
This is a nice feature. Thank you for your suggestion, @bildin!
