### ISSUE TITLE
Please add feature to add customized SNI address

### ISSUE THREAD

**Issue by Pillen1** [kittoku/Open-SSTP-Client#127]
it would be great if you add this feature to change the deafult SNI addresses to a customized one for our SSTP servers!

**Comment by kittoku** [comment]
In what scenario do you need to modify SNI address? I'm just curious.

**Comment by Pillen1** [comment]
> In what scenario do you need to modify SNI address? I'm just curious.

in countries with restricted internets and firewalls that block VPN connections such as China, Russia, Iran ect... Sometimes connecting to a SSTP server with it's deafult SNI address will make the connection to be throttle and unstable; or lowering the speed. While it can be easily fixed in most of the scenarios with just changing the deafult SNI address of our SSTP server, to a customized one that can bypass those limitations and restrictions

**Comment by kittoku** [comment]
[osc-sni.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.6.5.1/osc-sni.apk) works?

**Comment by Pillen1** [comment]
> [osc-sni.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.6.5.1/osc-sni.apk) works?

it works like a charm! Really appreciate for adding this feature. SSTP servers are working great now with customized SNI. thanks a lot.
