### ISSUE TITLE
Could you work on OpenConnect client for Android too?

### ISSUE THREAD

**Issue by Pillen1** [kittoku/Open-SSTP-Client#128]
I'm really sorry to post this suggestion here and that's because i didn't find anywhere else to tell this to you so please accept my apology dear KOBAYASHI!

I just want to know if that's possible for you, please develop a standalone OpenConnect (AnyConnect) client for Android ae well just like you did with SSTP client (which works great!)

The only OpenConnect client for Android has been abandoned and it's developer said that it will no longer get any update :(

It would be great if you can make an OpenConnect client for Android with an option to disable UDP (DLTS) , support of TLS V1.3 , also option to set proxy and support of every type of certificate SSL.
Thanks in advance...

**Comment by kittoku** [comment]
Sorry, I won't.
