### ISSUE TITLE
Zyxel Keenetic connection

### ISSUE THREAD

**Issue by EU1KY** [kittoku/Open-SSTP-Client#13]
Hi,
This app is a great thing that allows connecting remote networks via the Keenetic Link SSTP tunnel. SSTP server can be enabled on most of Zyxel routers, and there is a Keenetic domain name service available out of the box. This makes access to remote network as easy as never before. 
The version 1.0.0 works like a charm, but the latest 1.0.4 fails to connect. Had to revert back to 1.0.0.

**Comment by kittoku** [comment]
I'm grad to hear that this app is of any help to someone else ( ´ ▽ ` ).

This latest version works normally in SoftEther servers. So, I am sorry to say, there is no reason to revert commits for me unless what causes your problem can be identified.

**Comment by igkhv** [comment]
+1 Mikrotik ROS 
The version 1.0.0 works, latest 1.0.4 fails to connect.

**Comment by kittoku** [comment]
How about releases between 1.0.0 and 1.0.4?

**Comment by igkhv** [comment]
only 1.0.0 works

**Comment by kittoku** [comment]
Thank you for reporting.

I think [this commit](https://github.com/kittoku/Open-SSTP-Client/commit/1b0625b7251b5ea7f3cf03f49048426563a93562) does something wrong (about Magic-Number implementation?). But I cannot exactly confirm which point is bad.

If you really want to use the latest version, providing a test server, including sending me a private key, may be a solution. Of course I cannot grantee this will solve the problem.

**Comment by EU1KY** [comment]
Hi Ittoku,
I can provide you SSTP access to my Keenetic for testing purposes.
Please contact me by email kuchura@gmail.com

**Comment by kittoku** [comment]
Please try [this beta](https://github.com/kittoku/Open-SSTP-Client/releases/download/BETA/osc-beta.apk)

**Comment by igkhv** [comment]
MikroTik ROS 6.45.8 long term work 1.0.4 beta

**Comment by EU1KY** [comment]
Beta works for me.

**Comment by kittoku** [comment]
@EU1KY, you can shutdown the server immediately. Thank you for contribution!

This fix will be included in the version 1.1.0.

**Comment by nastaransadra** [comment]
hi , I build this code and try to connect with the latest one. Unfortunately , it does not work. Is there any specific configuration with it?
