### ISSUE TITLE
[Feature Request] EAP-MSCHAPv2

### ISSUE THREAD

**Issue by tormentous** [kittoku/Open-SSTP-Client#131]
as the title say, can it be done?

**Comment by kittoku** [comment]
You mentioned just EAP-MSCHAPv2, not PEAP, didn't you?

**Comment by tormentous** [comment]
> You mentioned just EAP-MSCHAPv2, not PEAP, didn't you?

If both can be done, the better

**Comment by 2447776119A** [comment]
[qiwa.sa](url)

**Comment by kittoku** [comment]
Please try [osc-eap.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.7.1/osc-eap.apk). You need to select only `EAP-MSCHAPV2` in `Select Authentication Protocols`.

PEAP could not be implemented. It needs more effort for realizing TLS over TLS.

**Comment by tormentous** [comment]
> Please try [osc-eap.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.7.1/osc-eap.apk). You need to select only `EAP-MSCHAPV2` in `Select Authentication Protocols`.
> 
> PEAP could not be implemented. It needs more effort for realizing TLS over TLS.

I got this message
[2024-07-02 14:30:18.736] Establish VPN connection
[2024-07-02 14:30:19.915] SSL: ERR_UNEXPECTED_MESSAGE
[2024-07-02 14:30:19.927] Terminate VPN connection

**Comment by kittoku** [comment]
It look like that the app couldn't establish SSL session before it reaches authentication stage. 

Can you establish a VPN connection with the same server and another protocol(PAP or CHAP)?

**Comment by tormentous** [comment]
> It look like that the app couldn't establish SSL session before it reaches authentication stage.
> 
> Can you establish a VPN connection with the same server and another protocol(PAP or CHAP)?

Same results

**Comment by kittoku** [comment]
[On the previous version](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.7.1/osc-1.7.1.apk), the app have worked without problems?

**Comment by tormentous** [comment]
> [On the previous version](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.7.1/osc-1.7.1.apk), the app has worked without problems?

The previos version has same result as the one you shared too

**Comment by kittoku** [comment]
Could you try another SSTP client, such as Windows built-in one, to check if the server's configuration is OK?

**Comment by kittoku** [comment]
Is there any prolem, @tormentous?
