### ISSUE TITLE
error：ERR_UNEXPECTED

### ISSUE THREAD

**Issue by cying112115** [kittoku/Open-SSTP-Client#132]
There is a problem. After connecting to VPN, if I press the Home button to hide the APP to the background, lock the phone screen, and then unlock it, repeating the process twice, the VPN connection will be disconnected. Please help me look into this issue and tell me how to keep the connection after unlocking without being disconnected?

**Comment by kittoku** [comment]
I couldn't reproduce your error. I want to know your android version, device name and what the log said.
