### ISSUE TITLE
"Allow Apps" Feature

### ISSUE THREAD

**Issue by ScriptTiger** [kittoku/Open-SSTP-Client#14]
Hey, @kittoku! Awesome project!

Any plans on implementing an "allow apps" feature to only allow certain apps to connect through SSTP and everything else just uses the regular connection? This is a pretty standard feature in many proxy and VPN clients and is necessary to avoid conflicts since obviously many people will only want certain apps using the VPN and not all of them. It also improves performance, as well, since tunneling everything over a VPN could possible severely impact the performance of some apps that don't require VPN access.

**Comment by kittoku** [comment]
It looks a good feature. VpnService.Builder may have APIs to do that.

I keep this issue open, but please don't think that soon I will begin to try implementing it. I'm afraid the development of this repository is not a high priority.

**Comment by 18062942985** [comment]
When SSTP is often dropped for no reason, can the boss add disconnection and reconnection settings

**Comment by ytandogan** [comment]
Not an issue but a feature request:
I have been using the app almost a month now and I am really happy with it.
With "no battery restriction" app is stable. 
Feature Request: Multiple connection profile feature would be nice.

**Comment by ytandogan** [comment]
Just tested 1.5.0 on android 10. Client fails to connect with OSC: ERR_UNEXPECTED error. Where can I send the logs?
