### ISSUE TITLE
I cant connect by domain ***.softether.net but can connect by domain vpnazure.net.

### ISSUE THREAD

**Issue by arthurOmanko** [kittoku/Open-SSTP-Client#140]
I can't connect to my same server by domain ***.softether.net but can connect to it by domain ***.vpnazure.net (using intermediate servers).
I tried all settings on app in order to connect directly my server by ***.softether.net but all were ng.
I guess this app supports only direct TCP connection to softether VPN server but not UDP (UDP hole punching not supported)?
Because I'm closing all TCP port (or almost of all UDP) on my router.

Or the number of session connection can't be manipulated on this app? (normally pc version has selected 1-32 tcp connections) 

Please tell me current situation of your app.

thank you in advance.

**Comment by kittoku** [comment]
This app is a SSTP client. It never supports UDP hole punching becauses the protocol definition doesn't include it.

**Comment by arthurOmanko** [comment]
oh. Thank you for your fast reply.
I see. I can use by azure of softether after all (using intermediate servers). tks.

So this app cant manipulate the number of tcp connection? I confirmed always only 1 tcp connection when connecting.
If so, I hope you will implement the changing function in near future.

Or as one mistake, on google play, the URL of your site is shown as different one now.
-- on google play: https://github.com/kitoku/Open-SSTP-Client
-- real url site: https://github.com/kittoku/Open-SSTP-Client 
you or google should correct the wrong url.

very tks.

**Comment by kittoku** [comment]
Unfotunately, SSTP protocol don't support multiple connetion neither.

BTW, where in Google Play did you find the wrong url? I cannot find. Could you upload a screenshot?

**Comment by arthurOmanko** [comment]
google play : ***/kitoku/***
real url:          ***/kittoku/***

google play has missed one "t".
tks.

**Comment by kittoku** [comment]
Could you show me the exact point where you found the wrong URL?
![screenshot](https://github.com/user-attachments/assets/95a5324a-8c05-4e79-8ea6-c91ee9ed8b83)

**Comment by arthurOmanko** [comment]
Japanese version google play on PC.

![wrongURL](https://github.com/user-attachments/assets/a0e0a866-daf4-4c77-bcec-527e6e368330)

**Comment by kittoku** [comment]
I don't know why too (maybe auto translation did something), but I think this is not a big problem. The right URL can be reached via `App Support` section or the app's setting fragment.

Thank you for reporting!
