### ISSUE TITLE
Feature Request: Select Virtual HUB

### ISSUE THREAD

**Issue by zhouzhiwen2000** [kittoku/Open-SSTP-Client#143]
Is is possible to select different virtual hubs? I have a softether server with multiple virtual hubs and it seems to always connect to the DEFAULT hub. It would be nice to select another one.

**Comment by artdeell** [comment]
to connect to a different hub use `username@HUB` as the username instead of just `username`

**Comment by zhouzhiwen2000** [comment]
This works, thanks a lot!
