### ISSUE TITLE
VPN connections only last a few minutes

### ISSUE THREAD

**Issue by ScriptTiger** [kittoku/Open-SSTP-Client#15]
When the VPN is established, everything works really well. However, the VPN always closes with the following message after a few minutes:

The counter was exhausted:
sendEchoRequest

This app is really awesome for short-term connections, but does not work if you need to stay connected for things like ongoing communication apps, messaging, etc.
![Screenshot_20200519-202052_Open SSTP Client](https://user-images.githubusercontent.com/29940916/82326668-c47dff00-9a0f-11ea-9458-5d75eef7490d.jpg)

**Comment by kittoku** [comment]
Sorry, but I don't know how to solve your problem. Please see "Debugging" paragraph in README.md.

**Comment by ScriptTiger** [comment]
Will do, I'll update you as soon as I have time.

**Comment by ScriptTiger** [comment]
I'm closing this. My ISP has now blocked it.
