### ISSUE TITLE
Data loss up to 8% while running speedtest

### ISSUE THREAD

**Issue by andrewfer000** [kittoku/Open-SSTP-Client#17]
Hi there! I was testing out your app with the latest version of SoftEther VPN server and noticed that when I ran a speedtest I got decent speeds but high ping (>40ms), high jitter (>30ms), and most importantly data loss up to 8.0%. When on the other protocols the speeds will be higher, ping will be low (<30ms) and jitter would also be very low (<3ms) and there would usually always be data loss of 0.0% with the very rare case of being <0.8%. Is this because this app is in development still or is it just because Android does not like SSTP?

**Comment by kittoku** [comment]
I cannot tell the reason my app has less performance. As you mention, my lack of programming skill is likely the one.

The two other reasons I can come up with are

1. My app and the other protocol uses different test servers and routes.

2. SSTP is a TCP-over-TCP protocol. So it is natural that SSTP doesn't have good performance.

**Comment by andrewfer000** [comment]
Well SSTP works without issue on native clients such as the one found on Winsows and Linux so its most likley just this app. SSTP wasn't designed for Android anyway so I didn't really expect it to be perfect.
