### ISSUE TITLE
Add an option to not redirect gateway

### ISSUE THREAD

**Issue by gtrubach** [kittoku/Open-SSTP-Client#18]
Hi,

Is it possible to add an option to prevent gateway redirect when it's only required to access local network but not the internet itself?

**Comment by kittoku** [comment]
If the server give a local address 192.168.X.X to the client, you want to forbid the client to connect a global address like 13.114.40.48(github.com). 

Am I right?

**Comment by gtrubach** [comment]
Yes, but allow the client to connect to the global address using its current non-vpn connection (e.g. mobile or wifi connection). 

Let's say the client has an ip x.x.x.x from the mobile internet. He connects to the VPN and receives some local address from it, also the VPN server has some external IP assigned to it, e.g. y.y.y.y.

Currently if the client makes a request to the global address like github while connected to VPN he uses the VPN server network to do it (externally he will be y.y.y.y).

What I suggest is to be able to use the mobile network to make requests to global address without using VPN server. But at the same time be able to access local network from VPN server.

**Comment by sudanking** [comment]
Is there is a way to not redirect default gateway to the tunnel?

**Comment by kittoku** [comment]
I, also, want to know the answer...

**Comment by gtrubach** [comment]
There should be. I found that it also called split tunneling if I correct.

For example VPN Client Pro has such functionality - https://www.colucci-web.it/forum/viewtopic.php?t=517

Also in Windows it can be achieved via Powershell: See SplitTunneling option here - https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnection
"Indicates whether the cmdlet enables split tunneling for the VPN connection profile. When you enable split tunneling, traffic to destinations outside the intranet does not flow through the VPN tunnel. Specify a value of $True to enable split tunneling." 

I don't know how it's implemented though...

**Comment by kittoku** [comment]
I don't know, too (´-ω-`)

**Comment by Evengard** [comment]
This is done as routing setup. Actually, this is the line which redirects all the connections via the tunnel: https://github.com/kittoku/Open-SSTP-Client/blob/5971eb1e903d36a61ef1430563039b348c01a2a2/app/src/main/java/kittoku/opensstpclient/layer/IpTerminal.kt#L70

We just need to not add this route and instead add more specific routes to allow accessing only some ip addresses via vpn, and allowing all the others to be routed via the main connection (wifi or mobile connection).

**Comment by kittoku** [comment]
How about [this beta](https://github.com/kittoku/Open-SSTP-Client/releases/download/beta/osc-beta.apk)?  

Please try **Route Only packets to LAN** option

**Comment by gtrubach** [comment]
I tried it but now it cannot open anything :(

I disabled NAT on router for VPN connections, went to mobile network, checked new option, connected successfully to VPN, tried to open internal resources and global (e.g. google.com) and wasn't able to open them.

Do I need to setup something else except enabling new option?

**Comment by kittoku** [comment]
Thank you for testing. I will change the method.

BTW, in accessing to internal resources, you use private IPv4 addresses (like 192.168.*.*) and don't use domain names (like .home). Is this correct?

**Comment by gtrubach** [comment]
Usually I use domain names, but in this beta I tried both domain name and by IP. By domain name it wasn't able to resolve a name and by IP it wrote something like "no internet".

**Comment by kittoku** [comment]
Then, how about this, [osc-explicit.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/beta/osc-explicit.apk)

**Comment by gtrubach** [comment]
No luck :(

What I found is that global resources are accessible by the IP (e.g. 1.1.1.1) but not by the domain name. Internal resources are not accessible by either way.

If it helps I can provide you an access to my VPN with web server inside for testing.

**Comment by kittoku** [comment]
It is interesting. But I must say your contribution can be in vain. If you are ok with this, please give me test environment.

**Comment by gtrubach** [comment]
Can you please email me at g34wte-nosec@outlook.com? I will reply you back with the credentials and url.

**Comment by kittoku** [comment]
A mail was sent! Please check spam folder.

**Comment by gtrubach** [comment]
Replied you back.

**Comment by kittoku** [comment]
@gtrubach's  problem was solved. His contribution revealed that users who want to use this option must make sure that a private address to access belongs to assigned IP's network.

Thank you, @gtrubach! And also I really appreciate @Evengard's advice!

Yeah, I know, this client have to show assigned addresses. I know...
