### ISSUE TITLE
Timeout happens with 2FA

### ISSUE THREAD

**Issue by Lonli-Lokli** [kittoku/Open-SSTP-Client#20]
We have 2FA so seems like timeout causing vpn close almost immediately.

Please add setting with timeout (eg 30sec) before close

**Comment by kittoku** [comment]
Could you tell detail of your situation and the protocol of 2FA you use. There are several points where this app produces timeout exception, like establishing a SSL socket, authenticating in PPP and echoing in PPP/SSTP.

**Comment by Lonli-Lokli** [comment]
Here are all logs from app
22:35:18] Establish VPN connection
[22:35:23] The timer was over: proceedPap
[22:35:23] PPP layer turned down
[22:35:23] Terminate VPN connection

**Comment by kittoku** [comment]
In authenticating process, you have three seconds according to RFC1661. Normally the duration is long enough.

Can you specify the authentication protocol that you use? I think that this app cannot deal with it.

**Comment by Lonli-Lokli** [comment]
As I said we have 2factor authentication setup, eg when establishing connection vpn server sends push request to the application on phone and I have to accept it. And 4sec is not enough for this

**Comment by kittoku** [comment]
> vpn server sends push request to the application on phone and I have to accept it

Still I cannot understand the exact authentication protocol that you use. But this client doesn't implement such complicated process for authentication.

**Comment by Lonli-Lokli** [comment]
All I need for my issue is setting for timeout, not only the default 4sec

**Comment by kittoku** [comment]
Sorry, but I cannot add the complexity to my source for the necessity I cannot understand perfectly.

Feel free to fork! You can change anything as you wish!

**Comment by Lonli-Lokli** [comment]
Ok thanks for the proposal.
Just fyi, 3sec is not a requirement in rfc1661
The Restart timer  MUST be configurable, but SHOULD default to three (3) seconds.
