### ISSUE TITLE
ICMPv6 implementation for IPv6

### ISSUE THREAD

**Issue by kittoku** [kittoku/Open-SSTP-Client#21]
I found that this client should support ICMPv6 protocol to communicate through IPv6.

This is a known issue and I don't have enough time...

**Comment by kittoku** [comment]
PPP clients don't need global (unique local) unicast addresses, do they?

To be honest, I have never met the situation where IPv6 is really needed. So I'm not familiar with how it works in PPP.

**Comment by Evengard** [comment]
IPv6CP generates an EUI-64 which then in turn is used to generate a link-local address. After we got a link-local address then we can start to assign ourselves a global or unique-local unicast address. Which is not needed "per se", but is needed for any sort of meaningful communication. The only way to acquire this is via Router Advertisement / Router Sollicitation mechanism (part of Neighbor Discovery mechanism) as per RFC 4861.

Actually this mechanism is needed even with Link-Local addresses, as a client still needs to find its router and/or neighbors first to be able to route IPv6 packets at all, as Neighbor/Router discovery is actually a replacement for the ARP protocol in IPv4.

Also Neighbor/Router discovery is done as a subtype of ICMP protocol, yeah.

**Comment by Evengard** [comment]
Tbh I thought that the ARP/ND part of the stack is done in Android itself - and tbh it should be. I should try your latest client to try and see how it works in an IPv6 env... Then I can tell you more.

**Comment by Evengard** [comment]
I did a very quick test, and it seems like IPv6 is broken at all. I mean, the server doesn't detect any IPv6CP packets from the client at all, the client seems to not even trying to establish an IPv6 connection at all.

**Comment by kittoku** [comment]
How about [this latest version](https://github.com/kittoku/Open-SSTP-Client/releases/download/beta/osc-fc83992.apk). You already know, but please don't forget to push **SAVE** button.

And I never mean to rush you.

**Comment by Evengard** [comment]
Shame on me, I totally forgot about that save button =) Will test later.

**Comment by Evengard** [comment]
I've did a quick test with the latest beta and it actually works! I got assigned a global IPv6 address via Router Discovery mechanism and internet is working! Although with disabled IPv4 I get no IPv4 connection at all, but IPv6 works!
When enabling both IPv4 and IPv6 they both work via VPN without troubles.

**Comment by kittoku** [comment]
Thanks a lot, @Evengard! Now I am satisfied not to need to implement ICMPv6 (^∇^)

Still, this client has to retrieve the IPv6 address which the device's IP stack automatically configures in order to route IPv6 traffics. But it's another issue.

**Comment by Evengard** [comment]
FYI I checked the assigned addresses via `ip addr` command in the terminal. Although I guess there should be some kind of Java Android API to retrieve such information...

**Comment by kittoku** [comment]
I think so. You use `ip addr` with an app like [this](https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=ja)? No need for root permisson?

**Comment by Evengard** [comment]
Yes, no root required, although I'm using a different terminal application, but it doesn't really matters.
