### ISSUE TITLE
Failed to be authenticated: receiveChapFailure

### ISSUE THREAD

**Issue by a567765** [kittoku/Open-SSTP-Client#24]
Constantly getting this on connection. Credentials are correct, they work fine on "VPN Client Pro" from play market.
```
[01:05:46] Establish VPN connection
[01:05:46] Failed to be authenticated: receiveChapFailure
[01:05:46] PPP layer turned down
[01:05:46] Terminate VPN connection 
```

**Comment by kittoku** [comment]
You gave not enough information to solve. Please see Debugging section in README.md.

I, however, came up with the possibility that you use non-ascii characters in your username.

**Comment by a567765** [comment]
Sorry, i'm not qualified to debug and decrypt traffic on my own, maybe adding some verbose logging to app may help?
Username contains "\" in it, it looks like <domain>\<username>

**Comment by kittoku** [comment]
How about inputting just `<username>` or `<username>@<domain>`?

**Comment by a567765** [comment]
Hmm, looks like <username>@<domain> totally works! It says "Open SSTP Client connecting" in tray and shows red icon but it totally works. Thanks

**Comment by guiolpei** [comment]
Just to share my personal experience and in case it is useful for someone else: using `<username>@<domain>` instead of old syntax `<domain>\<user>` is necessary to avoid `receiveChapFailure` when connecting to a `Windows Server Essentials 2016 SSTP VPN`.

**Comment by kittoku** [comment]
I use the term `connecting` to indicate that this client is receiving and sending packets NOW. But `Open SSTP Client connected` is grammatically correct or non-confusing, isn't it?

I understand this is totally off-topic, but I want to hear native speakers' opinions.

**Comment by guiolpei** [comment]
In my opinion, `Open SSTP Client connected` is indeed less confusing. Using the word `connecting` makes it seem like the process of connecting to the VPN is not finished and therefore the connection has not been successfully established. Apart from this, great work!
