### ISSUE TITLE
Issue with App when vpn is with MFA 

### ISSUE THREAD

**Issue by karkafy** [kittoku/Open-SSTP-Client#25]
Hi, 

I have an SSTP VPN with Azure MFA . The app will not wait for authenticator to apporve the sign in and an error occured image attached . Ithink increasing the timer will solve the issue 
![20201013_001516](https://user-images.githubusercontent.com/45240091/95791055-3c173800-0ce9-11eb-869b-d7fe0f28dbb1.jpg)

**Comment by kittoku** [comment]
I sincerely hope that [this version](https://github.com/kittoku/Open-SSTP-Client/releases/download/beta/osc-long.apk) will work for you
