### ISSUE TITLE
Request faeture "Set TLS SNI"

### ISSUE THREAD

**Issue by atdx** [kittoku/Open-SSTP-Client#26]
Hi, I don't really know what this feature does, but could you consider adding it in the next update, this feature is in "VPN Client Pro" but requires an annual subscription to use it.

**Comment by kittoku** [comment]
You don't know SNI and still need it?

**Comment by atdx** [comment]
I think it's to deceive cellular operators, if we customize SNI by using a website that can be accessed without paying, so we can use SSTP for free internet, this method works in "OpenVPN Client Pro"
