### ISSUE TITLE
Bypass ssl

### ISSUE THREAD

**Issue by realsarm** [kittoku/Open-SSTP-Client#29]
Hi

I was wondering if we can use this as a normal PPTP vpn
Is this possible? How can I achieve this ?

**Comment by kittoku** [comment]
You cannot use PPTP on this app.

I think that android itself has PPTP feature.

**Comment by realsarm** [comment]
Yeah but I wants to programmatically connect the device to PPTP VPN
You mean even by modifying this project negotiatiotors class?

**Comment by kittoku** [comment]
I haven't read PPTP referene, but, I bet that PPTP could be implemented.

I, however, have no plan to implement it.
