### ISSUE TITLE
Master, can you give me a hand?

### ISSUE THREAD

**Issue by yiqifengfa** [kittoku/Open-SSTP-Client#3]
Hello, master, when I linked to my server, I grabbed the package and checked it. I found an error: TLSv1.2 connection established with cipher ecdhe-rsa-aes256-shalcp auth negotiation failed!
I have inquired some materials and suggested that I should use aes-256 encryption. I would like to ask how to use aes-256 for PAR authentication of PPP. If you are not busy, could you please give me some guidance?Thank you very much

**Comment by kittoku** [comment]
Could you show me your whole environment so that I can reproduce the error?

And don't call me master.

**Comment by yiqifengfa** [comment]
我的服务器是ROS认证，当我用 open-sstp 这个程序发送给ROS 认证时，ROS 没有返回我任何消息，我有个 测试账号，您如果有时间的话，能不能帮帮我。下面是测试账号----> username:aaaa      password:123456  server:hnly1.v15.cc

**Comment by yiqifengfa** [comment]
My server is ROS certified, and when I sent it to ROS certified with open-sstp, ROS did not return any messages. I have a test account, and if you have time, could you please help me?Here is the test account --> username:aaaa password:123456 server:hnly1.v15.cc

**Comment by kittoku** [comment]
I don't know so-called ROS. Please note a concrete service or software name, such as VPN Azure Cloud, and a complete method to simulate your environment exactly.

Remember, if you succeed in teaching me that, there will be a lot of difficulties left.
1) The service or software must be used for free.
2) I must be able to build a test server and a test client in my LAN or the service or software explicitly allow me to know a secret key to decrypt TLS-encrypted communications and debug this app.
3) When it comes to Extensible Authentication Protocol, which may be related to your issue, I have no idea to do.

Yes, you can keep this issue open, but of course there is no guarantee that I can fix or spare enough time for this issue. So I also strongly recommend you should seek other solutions like changing VPN protocol to more common one, disabling AES encryption or using more reliable commercial software, e.g. [this](https://play.google.com/store/apps/details?id=it.colucciweb.vpnclientpro).

**Comment by yiqifengfa** [comment]
ros is “routeros”  download address  https://mikrotik.com/download

**Comment by kittoku** [comment]
Have you ever tried to make `force-aes` **no**?
(https://wiki.mikrotik.com/wiki/Manual:Interface/SSTP#Server_configuration)

**Comment by yiqifengfa** [comment]
Yes, I tried, but I couldn't.

**Comment by yiqifengfa** [comment]
We tried sha-128 SHA-256 with VPN Azure, which was normal, but when we changed to ros, sha-128 could not use the SHA-256 that we currently forced the client to go, but ROS never received the log. Packets also have no data.

**Comment by kittoku** [comment]
I'm not an expert, so let me ask the below questions,
1) What does you mean by "sha-128 SHA-256"? They are terms in SSL/TLS layer, not SSTP or PPP?
2) You said "Yes, I tried, but I couldn't.". This meant that you **wanted** to disable AES but your administrator didn't allow it?

**Comment by yiqifengfa** [comment]
1.Encryption Protocol for SSTP Communication。
2.I tried to shut down force-aes, but after shutting down, we can't link. We grabbed the package and analyzed that the package we saw can be used normally with sstp-client, but the package we tried to send with Open-SSTP-Client has some differences and fewer parameters.
We want to support mschap2 | mschap1, but we don't have guidance on how to do it and hope to ask for your help.

**Comment by kittoku** [comment]
One more, you also already made `authentication` setting allow `pap`?

**Comment by yiqifengfa** [comment]
Four authentication methods are allowed:
mschapv2  mschapv1  chap  pap
I now suspect that authentication does not seem to support AuthProtocol PAR(0x0035.toshort ()) in pppframe. kt file in open-sstp-client without encryption,
The program does not return messages at this point:
![image](https://user-images.githubusercontent.com/38466610/61528127-9545dc80-aa50-11e9-97b3-7ae029c8bb1e.png)

**Comment by yiqifengfa** [comment]
This is my server configuration
![image](https://user-images.githubusercontent.com/38466610/61529003-d17a3c80-aa52-11e9-9671-97f395707136.png)

**Comment by kittoku** [comment]
Sorry, but `PAR` is a typo of `PAP`. Password Authentication Protocol(0xC023) is supported.

**Comment by yiqifengfa** [comment]
What should I do to make the Authentication Protocol pass? What should I change it to?

**Comment by kittoku** [comment]
hmm...I googled ROS, "sha-128 SHA-256" and MS-CHAP, but they are beyond what I can handle.

I'm afraid there is nothing I can do for you. Sorry.

**Comment by yiqifengfa** [comment]
Thank you very much.
At present, we find that the transmitted message is different by grabbing the package. I want to know that if I need to modify some code, I should modify that code.
1. I need to complete the message data sent by the client.
2. What should I do if I need to add CERT_HASH_PROTOCOL type?

**Comment by kittoku** [comment]
I don't have specific advice because I cannot understand your situation yet.
All I can say is to look over the code. Start with `Ctrl + F "CERT_HASH_PROTOCOL"`

This may sounds unkind. But I definitively conclude this is the most effective way for both of us.
