### ISSUE TITLE
Enhance the speed and lower the latency.

### ISSUE THREAD

**Issue by tormentous** [kittoku/Open-SSTP-Client#30]
Great work on the update/s :) but the performance is far less to the VPN C***nt Pro app in terms of speed. It would be better if you could improve the quality. I used the same SSTP account to compare.

**Comment by kittoku** [comment]
How about [this apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.0/osc-busy.apk)? It enables some kind of busy waiting. I cannot come up with where else to change now...

BTW, I am interested in how much the performances of the two apps are different. Would you mind telling me some results like bps, ping or jitter?

**Comment by tormentous** [comment]
> How about [this apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.0/osc-busy.apk)? It enables some kind of busy waiting. I cannot come up with where else to change now...
Maybe it takes too long to process the Threads? the Buffers? that may affect the Ping. IDK
> 
> BTW, I am interested in how much the performances of the two apps are different. Would you mind telling me some results like bps, ping or jitter?

Here I have links to the photos of their differences.
https://ibb.co/m5jyHZF
https://ibb.co/Dfj8RHL

**Comment by kittoku** [comment]
I tried increasing the buffer size of socket and this client to 1MiB ([this apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.0/osc-1M_buffer.apk)). Though, `socket.inputStream.read` size looks saturated up to 16KiB.

I think this may be one of the bottlenecks.

**Comment by kittoku** [comment]
@tormentous  
To be honest, still I don't know where to fix...
If you are really bored, please check that apk doesn't work in your environment too.

**Comment by tormentous** [comment]
> I tried increasing the buffer size of socket and this client to 1MiB ([this apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.0/osc-1M_buffer.apk)). Though, `socket.inputStream.read` size looks saturated up to 16KiB.
> 
> I think this may be one of the bottlenecks.

Sorry. I use Lenovo TB-7104I Android version 8.1.0,  I installed and tried both apks you sent, pretty much the same outcome, how about reducing the delay or timeouts I guess? 
> I think this may be one of the bottlenecks.
I am going to agree with this, if this is the core for connection?

**Comment by kittoku** [comment]
>reducing the delay or timeouts

This client gives receiving and sending processes each threads. So these parameters doesn't affect the performance, I think. 

Sorry. I leave this issue open, but I cannot solve this issue now.

**Comment by kittoku** [comment]
If you are still interested in this issue, please try [this v1.3.0 beta](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.1/osc-1.3.0_beta.apk). Perhaps you will get slightly improved performance.  

(With only CHACHA20-included cipher suites enabled, maybe more slightly improved)

**Comment by tormentous** [comment]
> If you are still interested in this issue, please try [this v1.3.0 beta](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.1/osc-1.3.0_beta.apk). Perhaps you will get slightly improved performance.
> 
> (With only CHACHA20-included cipher suites enabled, maybe more slightly improved)
Thank you for paying attention, it really improved! 
>  @`
![Screenshot_20210509-124737](https://user-images.githubusercontent.com/34568349/117560995-45bd1e80-b0c5-11eb-9850-42bf1d8afe19.jpeg)
`

**Comment by kittoku** [comment]
My apologies for misjudging. The bottleneck was not flushing SSL socket and 1ms delay, which you mentioned.

Until I realized flushing is necessary and  implemented it, there was no difference in performance between with delay and without delay. This issue was a good lesson for me!
