### ISSUE TITLE
Current Status when turned on Android 7.2 [No Connection Established]

### ISSUE THREAD

**Issue by Graius** [kittoku/Open-SSTP-Client#31]
I have Current Status when turned on Android 7.2 [No Connection Established]. Otherwise, the connection to the SoftEther VPN Server works. On Android 10, when enabled, the status changes.

**Comment by kittoku** [comment]
How about [this fix](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.2.0/osc-listen.apk)?

**Comment by kittoku** [comment]
I confirmed this problem is fixed on emulated Android 7.1.1.
If you still have a problem, please leave a comment!

**Comment by Graius** [comment]
Thank you, the version of the program you suggested is working correctly.
