### ISSUE TITLE
Add SNI extension

### ISSUE THREAD

**Issue by Ilya87** [kittoku/Open-SSTP-Client#33]
To access vpnazure.net (VPN relay, used by softether VPN), SSTP Client needs SNI extension. https://www.vpnusers.com/viewtopic.php?t=4838

**Comment by kittoku** [comment]
Anyone else wants SNI feature? It would be better if a test server were provided.

**Comment by Ilya87** [comment]
> Anyone else wants SNI feature? It would be better if a test server were provided.

Anyone can test by himself as softether vpn is free.

**Comment by kittoku** [comment]
As long as I follow [VPN Azure instruction](https://www.vpnazure.net/en/), I can connect to a server without problems (see the image below).

So I need a test server or complete procedures to reproduce your problem.

<img src="https://user-images.githubusercontent.com/38392245/118916038-2ba6fa00-b969-11eb-87c7-d4caa15c3982.jpg" width=25%>

**Comment by Ilya87** [comment]
Would you please be so kind to show settings you used to connect?

**Comment by kittoku** [comment]
I just followed the steps [here](https://www.vpnazure.net/en/) exactly.

Would you mind showing a client's log file?

**Comment by kittoku** [comment]
I hope you solved your problem. Reopen if you are still in trouble.
