### ISSUE TITLE
Failed to Verify Hostname

### ISSUE THREAD

**Issue by vVxiliVv** [kittoku/Open-SSTP-Client#34]
Hello!

I have a SoftEther server SSTP connection works fine if i disable hostname verification on other apps (iOS,android).
But when i disable "Verify Hostname" option in your app i still get the error "Failed to verify Hostname".
Your app looks so clean, that is why i want to use it.
Thank you!

**Comment by kittoku** [comment]
Please try [the version 1.3.1](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.3.1/osc-1.3.1.apk).

**Comment by vVxiliVv** [comment]
Thank you for your help!

Now i get NoPeerCertificate Error.

**Comment by vVxiliVv** [comment]
It works with a self signed certificate.

The problem is solved now!

The problem was that i made a certificate wih cloudflare, but that only works if i route the traffic trough it!

**Comment by vVxiliVv** [comment]
The same thing happens again.

Verify Hostname is unticked, hostname matches with the Softethers certificate.

[13:33:10] Establish VPN connection
[13:33:10] An unexpected event occurred:
SSLPeerUnverifiedException
No peer certificate
com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
kittoku.osc.layer.SslTerminal.createSocket(SslTerminal.kt:90)
kittoku.osc.layer.SslTerminal.initializeSocket$app_release(SslTerminal.kt:123)
kittoku.osc.layer.SstpClient.proceed$app_release(SstpClietnt.kt:166)
kittoku.osc.ControlClient$launchJobIncoming$1.invokeSuspend(ControlClient.kt:208)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[13:33:10] Terminate VPN connection

Thank you!
