### ISSUE TITLE
BufferUnderflowException under heavy traffic

### ISSUE THREAD

**Issue by tormentous** [kittoku/Open-SSTP-Client#35]
An unexpected event occurred:
BufferUnderflowException
java.nio.Buffer.nextGetIndex(Buffer.java:493)
java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:258)
kittoku.opensstpclient.misc.IncomingBuffer.getShort$app_debug(IncomingBuffer.kt:19)
kittoku.opensstpclient.layer.PppClient.proceedNetwork(PppClient.kt:245)
kittoku.opensstpclient.layer.PppClient.proceed$app_debug(PppClient.kt:356)
kittoku.opensstpclient.ControlClient$run$1.invokeSuspend(ControlClient.kt:293)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by kittoku** [comment]
Do you encounter this error frequently?

**Comment by tormentous** [comment]
During streams and heavy traffic

**Comment by kittoku** [comment]
Still stuck for reproducing this error. Could you share a link of streaming which cause your error?

**Comment by tormentous** [comment]
Either youtube or p*rnhub would do.
this happens occasionally when on heavy traffic, try to open chrome and open multiple tabs, then I use the youtube app, maybe this is because of my RAM since I only got 1GB?

> Still stuck for reproducing this error. Could you share a link of streaming which cause your error?

**Comment by kittoku** [comment]
I'm afraid I decided to leave this issue open but won't try fixing immediately. If there is a person who meet the same error, please report here.

It may not help you, but reconnection setting could be a workaround.

**Comment by kittoku** [comment]
I don't think payloads of SSTP can be fragmented, but it could be a cause. 

If you are interested in debugging, please try [osc-fragment.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.3.1/osc-fragment.apk)

**Comment by kittoku** [comment]
Reopen if anyone has additional information!
