### ISSUE TITLE
What is your recommendation for VPN Azure server?

### ISSUE THREAD

**Issue by zullusax** [kittoku/Open-SSTP-Client#37]
Settings - Enable only selected cipher suites.

The last 2 options, TLS_EMPTY and TLS_FALLBACK is pretty much useless(weak), so
can anyone tell which cipher is the best for security?

I don't care if the cipher slow down internet for a bit.

**Comment by kittoku** [comment]
Which protocol is most secure is depending on how the user thinks. If you don't have enough knowledge about cipher suites, don't use `Enable Only Selected Cipher Suites` option. Java will choose a reasonable suite for you.
