### ISSUE TITLE
Add "about" to the UI

### ISSUE THREAD

**Issue by zullusax** [kittoku/Open-SSTP-Client#38]
How about adding "About" section to the bottom of "Settings" panel so people can find here easily?

```
Log
Save Log (O  )
Select Log Directory

About
This app is developed by kittoku
Visit Github
Donate
```

Visit Github / Donate is a link. Tap will open a site.

**Comment by kittoku** [comment]
Finally, I just added the link to Setting tab. About tab seemed good, but it was too big change for its benefit.
