### ISSUE TITLE
Add "inifinite reconnection" option

### ISSUE THREAD

**Issue by zullusax** [kittoku/Open-SSTP-Client#39]
Currently Enable Reconnection only has Retry Count. I set it to 12345678 and RetryInterval to 3.

It'll be nice if your app has

```
Retry Inifinitely   (O   )
Retry Count
Retry Interval
```

If "Retry Inifinitely" is enabled RetryCount will grayed out. If disabled RetryCount will be tappable again.

**Comment by kittoku** [comment]
Once you establish a connection, retry counts are reset. So I think `12345678 and 3` must be enough because it gives you over one year.
