### ISSUE TITLE
LCP auth negotiation failed

### ISSUE THREAD

**Issue by weihaigang** [kittoku/Open-SSTP-Client#4]
LCP negotiation failed during PAP validation

**Comment by cnucky** [comment]
hello sir  
  I have the same question.Can you help me?
                                                       Thanks：）

**Comment by kittoku** [comment]
There may be hundreds of possible reasons why you failed and I cannot tell which is actual. All I can bet now is that your server use a self-signed certificate or doesn't have DHCP. 

If you give me more information which explains how to reproduce your error completely, I could do something. Sorry but there is no grantee I will do because I know VPN Azure Cloud only and don't wanna spend any money.

**Comment by cnucky** [comment]
My server did not use self-visa and I turned on DHCP

**Comment by cnucky** [comment]
My current status is that the SSL link is normal, but the LPP authentication in PPP fails.

**Comment by kittoku** [comment]
I'm not a wizard. Please treat me as a child and tell me COMPLETE explanation to reproduce your error, which include such as "How to install a server/service you use", "The exactly same settings you configured", etc.

Again, I don't wanna any money. I can't afford non-free software or extra hardware.

**Comment by cnucky** [comment]
Hi,
 I want to increase the agreement support for CHAP, but I can't Kotlin. I can provide a total fee, and I hope you can help me
Thanks：）

**Comment by kittoku** [comment]
I won't make a contract. This project is my hobby, not job. But I recognize some people need MS-CHAP.

By the way, if you don't mind paying some money, why don't you consider other options like [this](https://play.google.com/store/apps/details?id=it.colucciweb.vpnclientpro)?

**Comment by cnucky** [comment]
I need to build my own system to give users access to the line directly using their login account password. We're using Google Play now, but that's not the right way for users to use it, so I want to pay for a system of my own.

**Comment by kittoku** [comment]
I understand. I also recommend you use [VPN Azure Cloud](https://www.vpnazure.net/en/) or [SoftEther VPN Server](https://www.softether.org/). They are free and more reliable than mine :)

One more question, if you don't mind, why do you need CHAP protocol? I think PAP is enough secure because SSL/TLS layer already encrypts PPP or higher payloads very well.

**Comment by cnucky** [comment]
Because I am going to use radiu for authentication. If I put the data in the middle of the server, the transmission is in clear text. The network layer will leak my user information. Because SSTP is for security. I don't want to leak my user information at the network layer.

**Comment by cnucky** [comment]
If it is convenient, I would like to see the log output so that I can analyze the problem I am using. 
Thank you.：）

**Comment by kittoku** [comment]
"the log output"? My log where the app works normally helps you solve your problem?

Before discussing that, I want to see documents which explicitly show necessity of CHAP if you have. I don't know RADIUS well, but I cannot understand why the connection between SSTP-server and SSTP-client needs CHAP(I, somehow, can understand the connection between SSTP-server(RADIUS client) and RADIUS-server needs CHAP, or EAP).

**Comment by cnucky** [comment]
Yes, sstp and radius need to use chap or eap. This will be great.
I want to implement these functions myself, but my current level can only do analysis and ideas. My ability to write code is too poor.
So I want to seek your help, we will work together to complete him.
Thanks：）

**Comment by kittoku** [comment]
Let me comprehend. Your system may look like 

**A(SSTP client)** ----[connection X]---- **B(SSTP server)** ----[connection Y]---- **C(RADIUS server)**

A sends ID and PW to B. B communicates with C in order to whether A is registered user or not. And What you want is encrypt Y by chap. Am I right?

**Comment by cnucky** [comment]
yes

**Comment by kittoku** [comment]
And you understand that I made SSTP **client** software and have no knowledge of RADIUS and its communicating protocol, don't you?

**Comment by cnucky** [comment]
All I know is that I can't write code.
When the user submits the package to SSTP, the SSTP server receives and parses the packet and sends it to the radius server for authentication. Passing radius authentication returns the packet to SSTP and then SSTP returns the packet parsing to the user. If the radius authentication fails, the failed data is returned.
Some of the results feedback I have tested so far. If you support chap, you can solve the problem. If you can increase the logging options, this is convenient for subsequent development adjustments. It should be easy for you. We can find the problems we need to solve by getting the logs. 
We can work together to deal with this problem.
Thanks：）

**Comment by kittoku** [comment]
No. Authentication with PPP is separable from one with RADIUS, which I cannot handle.

Sorry but there is nothing I can do. You should ask people who made your SSTP server for your favor.

**Comment by cnucky** [comment]
Oh, thank you for your patience, I will write it for you to share.

**Comment by kittoku** [comment]
Don't share.
I'm afraid but I don't want to spend my time for this issue.
