### ISSUE TITLE
Rename the value DEFAULT to something else

### ISSUE THREAD

**Issue by zullusax** [kittoku/Open-SSTP-Client#41]
SSLVersion and AddressPrefixLength.

What is the default value?

It could explain more, like:

`DEFAULT (SSL3.0)`

**Comment by kittoku** [comment]
Which SSL version is selected depends on the device. Usually the device choose as secure version as possible. 

Without `Address Prefix Length` option, the app will calculate it according to the assigned IP address. So there is no default value. (cf. https://en.wikipedia.org/wiki/Private_network)
