### ISSUE TITLE
The server doesn't give a valid certificate

### ISSUE THREAD

**Issue by vVxiliVv** [kittoku/Open-SSTP-Client#42]
I get this error after i unticked  Verify hostname.
I use softether, and it works with SSTPConnect on iOS.

[15:10:39] Establish VPN connection
[15:10:39] An unexpected event occurred:
SSLPeerUnverifiedException
No peer certificate
com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
kittoku.osc.layer.SslTerminal.createSocket(SslTerminal.kt:90)
kittoku.osc.layer.SslTerminal.initializeSocket$app_release(SslTerminal.kt:123)
kittoku.osc.layer.SstpClient.proceed$app_release(SstpClietnt.kt:166)
kittoku.osc.ControlClient$launchJobIncoming$1.invokeSuspend(ControlClient.kt:208)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[15:10:39] Terminate VPN connection

**Comment by kittoku** [comment]
It doesn't look that verifying hostname cause this exception. The log says the server doesn't give a valid certificate. Please check if you can establish VPN connection with other SSTP client, including Windows-built-in client.

**Comment by vVxiliVv** [comment]
It works, i added the certificate to the trusted thingy on windows and i can in fact connect.
I can connect with SSTPConnect on iOS if i disable tls verification.

My certificates common name is my ip, and the server runs on port 8989.
I can connect with this app aswell.

https://play.google.com/store/apps/details?id=com.dzebb.sstp
The log from that app after connecting.

4:54:46 PM
VPN Established.
4:54:46 PM
dns 2: 8.8.4.4
4:54:46 PM
dns 1: 8.8.8.8
4:54:43 PM
Supported protocols:
  SSLv3
  TLSv1
  TLSv1.1
  TLSv1.2
Enabled protocols:
  TLSv1.1
  TLSv1.2
Using protocol: TLSv1.2
Using cipher : TLS_RSA_WITH_AES_128_CBC_SHA
Using peer principal : CN=37.221.215.187
4:54:43 PM
Handshake Completed
4:54:43 PM
Connecting...
4:54:43 PM
VPN is prepared.
4:54:43 PM
starting..
4:54:19 PM
Config is compatible.
4:54:19 PM
Checking config...

**Comment by kittoku** [comment]
hmm...then I cannot come up with any idea now.

**Comment by vVxiliVv** [comment]
If i enable vpn azure and use that hostname (.....vpnazure.net) it works.

**Comment by kittoku** [comment]
Maybe you failed on Android 6.0 and succeeded on Android 7.1?

**Comment by kittoku** [comment]
And they both failed with your own domain?

**Comment by vVxiliVv** [comment]
yes they do, only with your app tough :/

**Comment by vVxiliVv** [comment]
Nope, last time i tried was with 1.3.1 and it worked.
I will check out with a new server, i do not want to play around on my main server.

**Comment by vVxiliVv** [comment]
I freshly installed softether stable on a new vps.
Still i get this with your app.

Debian 9

SSLPeerUnverifiedException
No peer certificate

**Comment by vVxiliVv** [comment]
If i enable verification i get this:
[20:43:10] Establish VPN connection
[20:43:10] An unexpected event occurred:
Exception
Failed to verify the hostname
kittoku.osc.layer.SslTerminal.createSocket(SslTerminal.kt:85)
kittoku.osc.layer.SslTerminal.initializeSocket$app_release(SslTerminal.kt:123)
kittoku.osc.layer.SstpClient.proceed$app_release(SstpClietnt.kt:166)
kittoku.osc.ControlClient$launchJobIncoming$1.invokeSuspend(ControlClient.kt:208)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[20:43:10] Terminate VPN connection

**Comment by vVxiliVv** [comment]
If you have a telegram i can give my servers credentials.
(Its just a crappy vps...) so you can check whats up O.o

My servers ip is 37.221.215.160
SSTP runs on port 443.
Username is TSSOVPN
Password is L33thaxorz

I wonder that u can connect or not from android.
