### ISSUE TITLE
Timeout settings

### ISSUE THREAD

**Issue by Squeakimous** [kittoku/Open-SSTP-Client#45]
Hi, 

Could it be possible to add a timeout setting before disconnect or retry?

Regards,

**Comment by kittoku** [comment]
Need for what?

**Comment by Squeakimous** [comment]
Hi,

I'm currently testing your app (which is pretty cool by the way) with a MFA and if i'm fast enough, i'm able to achieve connection by approving connection with the MFA. But almost half the time i miss it because timeout is a bit too short (don't know what is the default timeout un your app).

Regards,

**Comment by Squeakimous** [comment]
Hi,

Sure, there it is 🙂

[2022-01-04 08:16:11.734] Establish VPN connection
[2022-01-04 08:16:15.230] The timer was over: proceedChap
[2022-01-04 08:16:15.231] PPP layer turned down
[2022-01-04 08:16:15.245] Terminate VPN connection


Log is empty when connection is successful though

Regards,

**Comment by kittoku** [comment]
Thank you for uploading, but please don't expect immediate update...

**Comment by Squeakimous** [comment]
Hi,

No problem 🙂

Regards,

**Comment by kittoku** [comment]
Please try [this beta](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.4.0/osc-timeout.apk).

You can change the timeout period at `PPP Authentication Protocol` setting.

**Comment by Squeakimous** [comment]
Hi,

Wonderful it fixed the issue we had when trying to connect through DUO MFA

Many thanks to you for issuing a fix so fast :-D

Regards

Stephane
