### ISSUE TITLE
Generate certificates on RouterOS error : routines:OPENSSL_internal:WRONG_TAG

### ISSUE THREAD

**Issue by aapapenkov** [kittoku/Open-SSTP-Client#46]
Hello!

I generated a certificate using RouterOS, but for some reason the application does not work with it.
generated certificate 20F23532511E917F:zzz.zzzz.ru:RU:ZZZZ:LTD:71:TULOBL:DNS:zzz.zzzzz.ru key-size:2048 key-curve:0 usage:80000005 valid:3650 for CA CA
Here is the log:

"
[2022-01-31 18:02:08.459] Establish VPN connection
[2022-01-31 18:02:08.509] An unexpected event occurred:
CertificateException
com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000b9:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
com.android.org.conscrypt.OpenSSLX509CertificateFactory.engineGenerateCertificate(OpenSSLX509CertificateFactory.java:274)
java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:362)
kittoku.osc.layer.SslTerminal.createTrustManagers(SslTerminal.kt:36)
kittoku.osc.layer.SslTerminal.createSocket(SslTerminal.kt:53)
kittoku.osc.layer.SslTerminal.initializeSocket$app_release(SslTerminal.kt:123)
kittoku.osc.layer.SstpClient.proceed$app_release(SstpClietnt.kt:160)
kittoku.osc.ControlClient$launchJobIncoming$1.invokeSuspend(ControlClient.kt:210)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
[2022-01-31 18:02:08.512] Terminate VPN connection

"

Thank you for your contribution!

**Comment by kittoku** [comment]
It looks like your certificate's format is not suited for the app. Please try another format.

BTW, `Select Cipher Suites` option was introduced for developer and its behavior is unstable. I highly recommend you should install your certificates directly to your device.
