### ISSUE TITLE
Feature request: Add multiple entries

### ISSUE THREAD

**Issue by soosp** [kittoku/Open-SSTP-Client#47]
Please add ability to save/recall multiple host/credentials entries.

**Comment by ScriptTiger** [comment]
Or maybe just general "profile" manager to save all config sets as profiles, as opposed to only credentials.

**Comment by kittoku** [comment]
Now the beta version with a multi-profile feature was released in Google Play. If you are interested, please try it.

**Comment by ScriptTiger** [comment]
Will do! Thank you so much!
