### ISSUE TITLE
Buffer Size mislabeled.

### ISSUE THREAD

**Issue by andrewfer000** [kittoku/Open-SSTP-Client#48]
![Screenshot_20220319-151259.png](https://user-images.githubusercontent.com/9620913/159135329-ea6af697-e273-479c-b87a-b058d2f3cc87.png)

I am assuming one of these is incoming and the other is outgoing. Just curious which one is which.

**Comment by kittoku** [comment]
The setting below is for outgoing buffer.

Thank you for noticing! I will fix.
