### ISSUE TITLE
Keenetic test environment is wanted

### ISSUE THREAD

**Issue by kittoku** [kittoku/Open-SSTP-Client#54]
Keenetic users have been reported v1.5.0 or newer versions doesn't work (#53 and Google Play). I don't officially support keenetic products, but this time I think this problem should be solved for non-censored communications .

If there is anyone offering a test server and an account, please contact me.

**Comment by amokkatgithub** [comment]
Hey. How to privately provide you access data? I have same errors on 1.5.1 (unexpected)/1.5.2 (packet size), but server is not Keenetic.

**Comment by kittoku** [comment]
Thank you for contributing. My e-mail address is displayed on the Google Play's page. Please use it.

**Comment by kittoku** [comment]
I hope [this fix](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.2/osc-reject.apk) will work for you.

**Comment by amokkatgithub** [comment]
Thanks, it works

**Comment by kittoku** [comment]
a Keenetic user also succeeded to connect.

Thank you very much, @amokkatgithub !
