### ISSUE TITLE
No Internet after reconnection

### ISSUE THREAD

**Issue by tormentous** [kittoku/Open-SSTP-Client#57]
as the title says, everything is good but when a successful reconnection is made by the app, it could not browse the web unless disconnected and connected again. also please add a reconnect button in the notification. thanks!

**Comment by kittoku** [comment]
Sorry but this is not reproducible issue. Maybe you set reconnection interval too short.

**Comment by tormentous** [comment]
is it possible to add a reconnect button in the notification? maybe it could reproduce such event

**Comment by Reza-Mortazavi** [comment]
Same happens to mine. 

Open SSTP Client gets error SSTP_CONTROL: ERR_ABORT_REQUESTED or OSC: ERR_UNEXPECTED and disconnects from a dedicated server, then after 5 seconds of Retry Interval it seems to get reconnected with correct VPN sign in status bar, but there is no internet on device's Allowed Apps. 
Excluded apps are connected through normal internet connection.
This requires direct intervention, stopping and starting client may solve the problem, at least until the next disconnect. This is always happening.

This is a great app and Thank you for your efforts, I appreciate any idea you may offer, and let me know if any piece of information I can offer to solve this.

Regards.
