### ISSUE TITLE
No option to set static custom ip settigs

### ISSUE THREAD

**Issue by AMajor-C** [kittoku/Open-SSTP-Client#58]
Please add a feature to set static ip settings

**Comment by mfoolady** [comment]
You cannot specify IP addresses directly to use the SSTP connection

**Comment by AMajor-C** [comment]
> You cannot specify IP addresses directly to use the SSTP connection

Really ? say it to built-in client for windows

**Comment by mfoolady** [comment]
Since 2016, the CA/Browser Forum made SSL certificates for private IP/reserved IP and local server name with a non-public domain name suffix invalid and asked certificate authorities to revoke any such SSL certificates. Because such reserved IP addresses and local server names (intranet) are not unique, they are easy to impersonate by attackers to commit man-in-the-middle attacks and get unauthorized access to the data. Hence, publicly trusted certificate authorities can no longer secure such IPs. You can get a self-signed SSL certificate for private IPs and intranet addresses, though.

**Comment by maziarkabir** [comment]
But I use Softether clients with Ip.
Its configured only SSTP!

**Comment by mfoolady** [comment]
`Softether VPN protocol` (ethernet over HTTPS) is different from `MS-SSTP VPN`

**Comment by xumingxin7398** [comment]
I want this feature too, other clients support ip settings without a domain.

**Comment by kittoku** [comment]
Which address will be assigned should be handled by a server side. And this kind of feature is not implemented in Windows-built-in client and SoftEther's.

**Comment by AMajor-C** [comment]
![изображение](https://user-images.githubusercontent.com/7958892/203484576-11cac785-286b-4d77-9aa9-3021c1d0f375.png)
![изображение](https://user-images.githubusercontent.com/7958892/203484647-7e81d69f-b175-472f-9b1e-ecc35c86aaf8.png)


> Which address will be assigned should be handled by a server side. And this kind of feature is not implemented in Windows-built-in client and SoftEther's.

Srsly ? Then what is that ?

**Comment by kittoku** [comment]
My bad. I didn't see the lower layer. 

But I am still hesitating to implement a feature like this. I think that an IP address should be assigned according to an user's ID (like MAC address in DHCP) and I don't want to add a feature for maintainability unless it's needed by significantly many users.

**Comment by AMajor-C** [comment]
> My bad. I didn't see the lower layer.
> 
> But I am still hesitating to implement a feature like this. I think that an IP address should be assigned according to an user's ID (like MAC address in DHCP) and I don't want to add a feature for maintainability unless it's needed by significantly many users.

Sounds nice BUT softether's virtualnat doesnt support username-ip binding or mac-ip binding it is cause why i requested the feature.

**Comment by kittoku** [comment]
Please try [osc-static.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-static.apk) and use `Static IPv4 Address` preference.

**Comment by AMajor-C** [comment]
> Please try [osc-static.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-static.apk) and use `Static IPv4 Address` preference.

I have tested and it works godd thak you.

**Comment by AMajor-C** [comment]
BTW can you add option 33 and 252 accepting from server's dhcp ? 
33 - pushes routes 252 - proxy settings

**Comment by kittoku** [comment]
This client doesn't have DHCP stack. So maybe I couldn't do that.

**Comment by AMajor-C** [comment]
> This client doesn't have DHCP stack. So maybe I couldn't do that.

Oh got it.
I see you also added http proxy option that's nice what do you think about socks?

**Comment by kittoku** [comment]
I won't implement it at least this time. I need knowledge, time and necessity.

Please notice we are getting off-topic.
