### ISSUE TITLE
suggestion: tag releases

### ISSUE THREAD

**Issue by IzzySoft** [kittoku/Open-SSTP-Client#6]
Great to see another FOSS security app! May I suggest you [tag your releases](https://github.com/kittoku/Open-SSTP-Client/releases) and attach the APKs there? That way they…

* don't "bloat" the repo itself (think of contributors forking and cloning)
* APKs are easier found (no walking through a bunch of directories)
* I could grab your app and "promote" it via [my repo](https://apt.izzysoft.de/fdroid)
* we could probably even bring it to [F-Droid](https://f-droid.org/) which prefers to build from tags (as that way updates can be detected easier)

Thanks for considering!

**Comment by kittoku** [comment]
> don't "bloat" the repo itself (think of contributors forking and cloning)

I have been concerned about this problem. Thank you for advising!

**Comment by IzzySoft** [comment]
Gladly :smiley: Please let me know when there're tags available with APKs attached (e.g. by updating this issue once more – I guess you've closed it by accident, as there is no release tag yet), for the third bullet point (and probably going for the 4th as well if you want).

**Comment by kittoku** [comment]
Sorry for my impatience. Now tags and releases are available.

**Comment by IzzySoft** [comment]
Thanks! As promised: bullet point 3. Your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/kittoku.opensstpclient) in about 23h (next sync; I was back late today and didn't make it before today's sync).

Now, if you want to, you can add to your Readme that the app can be installed using the F-Droid client with my repo enabled. My scanner says it looks fine for f-droid.org (which has stricter rules than my repo, and strictly compiles from source, not allowing any binaries). If you wish, I can start the process of getting your app there (disclosure: I'm one of the maintainers). Just let me know.

**Comment by kittoku** [comment]
I'm afraid that now I don't want to register my app with f-droid officially for some private reasons.
Of course, your redistributing are welcome under MIT license (*^ーﾟ)b

Anyway, thanks for your advice again.

**Comment by IzzySoft** [comment]
I of course accept that even without knowing the reasons (though I wonder, I won't press) – it was just an offer. Be welcome to pick it up should you change your mind.

Thanks for your support!
