### ISSUE TITLE
Keep showing error

### ISSUE THREAD

**Issue by Aprinnetwork** [kittoku/Open-SSTP-Client#60]
Hi
There is the problem with the app. It only connects to VPNGATE listed servers and for those of us who have got theirown servers which are based on Softether Vpn it keeps showing a error "ERR_UNEXPECTED". There is no doubt that the app is second to none in supporting this protocol; but not accepting other servers is a major obstacle for those who like me run their own VPN server. 
Any help with that regard is appreciated.

**Comment by kittoku** [comment]
Please upload the log

**Comment by Aprinnetwork** [comment]
I enter user and pass correctly. Here is the logfile: 
[log_osc_20221001130100.txt](https://github.com/kittoku/Open-SSTP-Client/files/9689991/log_osc_20221001130100.txt)

**Comment by kittoku** [comment]
Disable `Verify Hostname` option and never forget to install your server's certificate if it's self-signed.

**Comment by Aprinnetwork** [comment]
Thank's. But another error appears. 
[log_osc_20221001154328.txt](https://github.com/kittoku/Open-SSTP-Client/files/9690273/log_osc_20221001154328.txt)

**Comment by Aprinnetwork** [comment]
It's working. Thank you for your time and consideration. Best wishes.
