### ISSUE TITLE
Connecting via proxy 

### ISSUE THREAD

**Issue by Aprinnetwork** [kittoku/Open-SSTP-Client#65]
Hello again. I'm just wondering if it's possible to have the option to connect via the proxy for restricted environments in the coming updates of the app; if there would be any updates.
Thank you for your time and consideration.

**Comment by kittoku** [comment]
You meant HTTPS proxy?

**Comment by Aprinnetwork** [comment]
Yes; exactly both http and https.

**Comment by Aprinnetwork** [comment]
🤔🤔

**Comment by kittoku** [comment]
I tried implementing proxy feature, which uses CONNECT method and is officially mentioned in SSTP reference.

Please test [osc-proxy.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-proxy.apk). You can specify the proxy server in the `SETTING` tab.

**Comment by Aprinnetwork** [comment]
> I tried implementing proxy feature, which uses CONNECT method and is officially mentioned in SSTP reference.
> 
> Please test [osc-proxy.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-proxy.apk). You can specify the proxy server in the `SETTING` tab.

Really appreciate your time and consideration. Your are really a lifesaver. ⚘⚘

**Comment by Aprinnetwork** [comment]
I Don't tend to be gum in the hair; and thanks for your effort to follow my request, but the proxy option works only without authentication.

**Comment by kittoku** [comment]
Does the authentication you meant use Base64 encoding and negotiate in HTTP (not HTTPS)?

**Comment by Aprinnetwork** [comment]
I use username and password in order to connect to my proxy server; thus the option in the app only accept a connection to proxy server without username and password. I use Squid Proxy script on my server. Lastly, pardon me for the lack of info that I have; current situation made me ask you for a lot favor. Again really appreciate your time.

**Comment by kittoku** [comment]
Please try [osc-proxy-auth.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-proxy-auth.apk).

Remember, your proxy username and password are base64-encoded, but not encrypted.

**Comment by Aprinnetwork** [comment]
> Please try [osc-proxy-auth.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-proxy-auth.apk).
> 
> Remember, your proxy username and password are base64-encoded, but not encrypted.

It worked. Thanks a lot. I wish you the best of two words my dear friend. Your help and contribution worth billions to me. 🙏🏻🙏🏻🙏🏻
