### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Apanj** [kittoku/Open-SSTP-Client#66]
In xiaomi antivirus powered by Avast, the program by version 1.5.8.1 downloaded from Google play store , detected as trojan. 
![Screenshot_2022-10-25-20-40-23-173_com miui securitycenter](https://user-images.githubusercontent.com/88619203/197840459-8486240b-97c5-433d-940e-6aef5598b51e.jpg)

**Comment by kittoku** [comment]
Are [the past releases](https://github.com/kittoku/Open-SSTP-Client/releases) also detected as torojon by Avast?

**Comment by Apanj** [comment]
> Are [the past releases](https://github.com/kittoku/Open-SSTP-Client/releases) also detected as torojon by Avast?

I checked version 1.5.5 too. It is the same!

**Comment by kittoku** [comment]
Hmm...I don't know why Avast sees this app as trojan. Please feedback the report to Avast or exclude the app from scanning if the notice is annoying to you.

Of course, if you are ultimately careful, you can build the app from the source with Android Studio by your own hand.
