### ISSUE TITLE
Security threat

### ISSUE THREAD

**Issue by mfoolady** [kittoku/Open-SSTP-Client#70]
**My phone detects it as malware**

![photo_2022-10-27_21-40-34](https://user-images.githubusercontent.com/59839339/198367255-725fa9a1-df87-4862-9e16-28b2f443167f.jpg)

**Comment by kittoku** [comment]
Now I am communicating with Avast Support Center. Please wait.

**Comment by AlirezaSafari7** [comment]
🧬 Detections: 1 / 65

⛔️ Avast-Mobile
  ╰ Android:Evo-gen [Trj]

**Comment by kittoku** [comment]
I was told that the detection was false positive and this issue would be fixed within 24 hours.

Please let me know if you are still warned in 24 hours, @mfoolady.

**Comment by AlirezaSafari7** [comment]
> I was told that the detection was false positive and this issue would be fixed within 24 hours.
> 
> Please let me know if you are still warned in 24 hours, @mfoolady.

problem solved, thank you.

**Comment by AlirezaSafari7** [comment]
🧬 Detections: 1 / 66

⛔️ Acronis
  ╰ suspicious

⚜️ Link to VirusTotal

**Comment by kittoku** [comment]
Thank you all. I will be communicating with Acronis then.

I'm afraid, but may I have your words that you confirmed Avast is not warning now on YOUR PHONES, not VirusTotal?

**Comment by mfoolady** [comment]
@kittoku 
I confirm that there is no more alert about virus protection

**Comment by mfoolady** [comment]
I see the malware alert again

**Comment by kittoku** [comment]
Now nothing has been detected on [VirusTotal](https://www.virustotal.com/gui/file/d7349d55828a743c8df06269e7ae279eb2e7c189cabc2e451b4efdc7fd653eb4/detection).

I began to realize that it is almost impossible to handle all false positive detections by only myself.

**Comment by mfoolady** [comment]
when I install the app from google play I see the malware alert but when I install it from the latest apk release there is no alert

**Comment by kittoku** [comment]
I installed [Avast](https://play.google.com/store/apps/details?id=com.avast.android.mobilesecurity),  but it says "secure to open" Open SSTP Client, which is got on Google Play.
