### ISSUE TITLE
The app isnt working for me and my friends and family

### ISSUE THREAD

**Issue by kian6639** [kittoku/Open-SSTP-Client#81]
It gives errors usually being PAP: err_timeout SSL err time out, which i assume are normal but then therea sstp control: err abort requested, which is concerning

None of th servers/hostnames work 
I dont know if its of any use but we are in iran

**Comment by kavehzotac** [comment]
The problem is from the infrastructure side and you should be patient until this problem is solved. It has nothing to do with the program or service

**Comment by kittoku** [comment]
I am sorry to say I cannot come up with what I can. But there are still many people who can connect to [VPN Gate](https://www.vpngate.net/en/) from Iran. Please take a look on [the access log](https://www.vpngate.net/en/lastlog.aspx).

I recommend that you should try other servers, protocols or solutions.

**Comment by kian6639** [comment]
Kavehzotac what do you mean? They took it down probably, they arent going to fix it because they are taking vpns down because of recent protests

**Comment by kavehzotac** [comment]
on mci is fine

**Comment by kian6639** [comment]
Im using mci too but it doesent work baw
