### ISSUE TITLE
Friendly Request 

### ISSUE THREAD

**Issue by AlexMans1608** [kittoku/Open-SSTP-Client#85]
Hi my awesome friend
I leave this request in Google play store but you didn't answer because you didn't see or don't have time sir. I just want you to choose a better ICON for this awesome application
Icon is so important when people want to choose a sstp client in android between two or more application like each other, i test all of them but your work is priceless, i hope you consider my request sir. Thank you for your time.

**Comment by khashayarnazari** [comment]
> Hi my awesome friend
> I leave this request in Google play store but you didn't answer because you didn't see or don't have time sir. I just want you to choose a better ICON for this awesome application
> Icon is so important when people want to choose a sstp client in android between two or more application like each other, i test all of them but your work is priceless, i hope you consider my request sir. Thank you for your time.

**Comment by Amirbarzegari** [comment]
Hi,
I'm a designer and willing to do this if @kittoku is ok.

**Comment by kittoku** [comment]
Thanks for your proposals, but I like my icon.
