### ISSUE TITLE
Cannot make the SSTP client to work

### ISSUE THREAD

**Issue by alphbtgm** [kittoku/Open-SSTP-Client#92]
I want to use the SSTP client to connect to VPNAzure for Softether. I did take the self signed certificate from sofether server (after changing the cert to vpnazure) and install it in the android but I always get no peer certificate

any suggestion would be appreciated.

**Comment by kittoku** [comment]
Normally, you don't need to install the server's certificate because SSL uses VPN Azure's certificate.

If you use `Add Trusted Certificates` option which denies VPN Azure's certificate, please disable it.

**Comment by alphbtgm** [comment]
Thanks kittoku. 

In the public page you wrote: "Your device needs to install a self-signed certificate and disable Verify Hostname option to access to a server using it". This is the reason I installed the cert. Before installing it, the error was: failed to verify the hostname.

I am using the standard setting in softether server, Also, I am using sstp client osc1.1.0 as later versions are not compatible with my tablet. But I did use many other sstp android app and I get errors in establishing the connection. therefore,. there is something wrong in my configurations. 

I suppose the option "add trusted certificates" is in the newer versions as the option I have in the SSTP client is: select trusted certificates (which would select a folder).

**Comment by alphbtgm** [comment]
I did cancel the folder for "select trusted cert" and disabled "verify hostname", and uninstalled the certificates, but still connection failed and the error is "no peer certificate".

I will be grateful for the feedback.

**Comment by kittoku** [comment]
>But I did use many other sstp android app and I get errors in establishing the connection.

So at first you need to make sure that your server's configurations and the procedures you take are correct. Please follow [the manual which SoftEther provides](http://www.vpnazure.net/en/) exactly. If you succeed to connect from Windows (or other clients on PC), then try Android's apps.

**Comment by alphbtgm** [comment]
I am able to connect with the server through softether client, and with windows sstp. So, I have no problem in the server or the client in windows configurations. my issue is about sstp in android. I need sstp because I think it is the only method that I can connect with to the server through Nat-T.

**Comment by kittoku** [comment]
So I'm afraid I don't know what to do, Maybe it's because of your device or your Android's version.

**Comment by alphbtgm** [comment]
I am happy to close the issue like this. But please just guide me through the process that I need to follow in the sstp client android:

1# install the apk in the device.
2# host name: vpnxxxxxx.vpnazure.net
3# User name: xxx@VPNHubName
4# Password: xxx
5# Port 443, MRU: Default, MTU: Default, Address Prefix: Default, SSL Protocol: Default
6# Enable: PAP, Enable: MS-Chapv2
7# Enable: IPv4, Disable: IPv6
8# Enable: "Disable Hostname Verifier".
9# Disable: Decryptable Mode
10# Trusted Certificates: no folder selected.
11# In the server: enable sstp connection.

Is this all, or am I missing some needed configuration?

**Comment by kittoku** [comment]
If 11# means also including enabling VPN Azure, I don't think you are missing something.

**Comment by alphbtgm** [comment]
Yes, indeed, VPN Azure is enabled, otherwise I won't be able to connect through windows.

Thank you kittoku.
