### ISSUE TITLE
Feature request: Support SoftEther protocol with UDP acceleration

### ISSUE THREAD

**Issue by filamento** [kittoku/Open-SSTP-Client#97]
Dear Sir,

Do you have plans to support SoftEther protocol directly, without SSTP ?

It would be very nice to have it, because it's really fast with UDP acceleration and can also work with pure user/password authentication, without requiring certificates.

There's an app called "SSTP Connect" for iOS devices that works really well for this, but unfortunately it doesn't exist for Android :(

**Comment by kittoku** [comment]
Sorry, but I won't. I want to keep this app simple.
